export const CLIENT_TEXT = {
  common: {
    breadcrumb: {
      home: 'Trang chủ',
      cart: 'Giỏ hàng',
      checkout: 'Thanh toán',
      orderSuccess: 'Đặt hàng thành công',
      orderTracking: 'Theo dõi đơn hàng',
      returns: 'Đổi/Trả hàng',
      profile: 'Hồ sơ của tôi',
      account: 'Tài khoản',
    },
    actions: {
      viewAll: 'Xem tất cả',
      viewDetails: 'Xem chi tiết',
      cancel: 'Hủy',
      confirm: 'Xác nhận',
      apply: 'Áp dụng',
      submit: 'Gửi',
      close: 'Đóng',
      save: 'Lưu',
      delete: 'Xóa',
      edit: 'Chỉnh sửa',
      add: 'Thêm',
      search: 'Tìm kiếm',
      back: 'Quay lại',
      continue: 'Tiếp tục',
      checkout: 'Thanh toán',
      addToCart: 'Thêm vào giỏ hàng',
      buyNow: 'Mua ngay',
    },
    status: {
      all: 'Tất cả',
      pending: 'Chờ xác nhận',
      processing: 'Đang xử lý',
      shipping: 'Đang giao',
      delivered: 'Đã giao',
      cancelled: 'Đã hủy',
      refunded: 'Đã hoàn tiền',
    },
    messages: {
      loading: 'Đang tải...',
      noData: 'Không có dữ liệu',
      error: 'Đã xảy ra lỗi',
      success: 'Thành công',
    },
  },

  cart: {
    title: 'Giỏ hàng của bạn',
    empty: {
      title: 'Giỏ hàng trống',
      description: 'Chưa có sản phẩm nào trong giỏ hàng. Hãy khám phá các sản phẩm tuyệt vời của chúng tôi!',
      action: 'Tiếp tục mua sắm',
    },
    selectAll: 'Chọn tất cả',
    productCount: (count: number) => `${count} sản phẩm`,
    subtotal: 'Tạm tính',
    discount: 'Giảm giá',
    shipping: 'Phí giao hàng',
    freeShipping: 'Miễn phí',
    total: 'Tổng cộng',
    freeship: {
      remaining: (amount: string) => `Mua thêm ${amount} để được Miễn phí vận chuyển`,
      achieved: 'Đơn hàng đã đủ điều kiện Miễn phí giao hàng',
    },
    coupon: {
      placeholder: 'Nhập mã giảm giá',
      apply: 'Áp dụng',
    },
    vatNote: 'Đã bao gồm VAT nếu có',
    proceedCheckout: 'TIẾN HÀNH THANH TOÁN',
    trustBadges: {
      secure: 'Bảo mật thanh toán',
      returns: 'Đổi trả miễn phí 60 ngày',
    },
    crossSell: 'SẢN PHẨM BẠN CÓ THỂ THÍCH',
  },

  checkout: {
    title: 'Thông tin giao hàng',
    payment: 'Hình thức thanh toán',
    breadcrumb: {
      cart: 'Giỏ hàng',
      shippingInfo: 'Thông tin giao hàng',
      paymentStep: 'Thanh toán',
    },
    addressBook: {
      title: 'Chọn từ sổ địa chỉ',
    },
    form: {
      name: 'Họ Tên',
      namePlaceholder: 'Họ Tên đệm và Tên',
      phone: 'SDT',
      phonePlaceholder: 'Số điện thoại',
      email: 'Email',
      emailPlaceholder: 'Email (Không bắt buộc)',
      address: 'Địa chỉ',
      note: 'Ghi chú',
      notePlaceholder: 'Nhập ghi chú',
      salutation: {
        male: 'Anh',
        female: 'Chị',
      },
      province: 'Tỉnh/Thành phố',
      district: 'Quận/Huyện',
      ward: 'Phường/Xã',
      loading: 'Đang tải...',
    },
    validation: {
      requiredName: 'Vui lòng nhập họ và tên',
      requiredPhone: 'Vui lòng nhập số điện thoại',
      invalidPhone: 'Số điện thoại không hợp lệ',
      requiredAddress: 'Vui lòng nhập địa chỉ chi tiết',
      requiredCity: 'Vui lòng nhập tỉnh / thành phố',
      requiredDistrict: 'Vui lòng nhập quận / huyện',
      requiredWard: 'Vui lòng nhập phường / xã',
    },
    paymentMethods: {
      cod: 'Thanh toán khi nhận hàng',
      zalopay: 'Thanh toán qua Zalopay',
      zalopayDesc: 'Hỗ trợ mọi hình thức thanh toán',
      momo: 'Ví điện tử MoMo',
      vnpay: 'VNPAY / VietQR',

    },
    orderSummary: {
      title: 'Chi tiết thanh toán',
      productTotal: 'Tổng giá trị sản phẩm',
      shippingFee: 'Phí giao hàng',
      subtotal: 'Thành tiền',
    },
    placeOrder: 'Đặt hàng',
    success: {
      title: 'Đặt hàng thành công!',
      orderId: 'Mã đơn hàng',
      continueShopping: 'Tiếp tục mua sắm',
    },
    returnPolicy: 'Nếu bạn không hài lòng với sản phẩm? Bạn hoàn toàn có thể trả lại sản phẩm.',
    help: {
      title: 'Gặp sự cố khi thanh toán?',
      desc: 'Kiểm tra kết quả giao dịch hoặc thử lại với phương thức khác.',
      link: 'Xem kết quả',
    },
    freeshipAlert: 'Đơn hàng đã được Miễn phí vận chuyển',
    socialProof: 'Có 6 người đang thêm cùng sản phẩm giống bạn vào giỏ hàng.',
    wallet: 'Ví Voucher',
    emptyCart: 'Chưa có sản phẩm nào',
    cartItemCount: 'Đơn hàng ({count} sản phẩm)',
    ticketRemaining: 'Còn {count}',
    ticketExpiry: 'HSD: {date}',
    walletVoucher: 'Ví Voucher',
    enterCouponCode: 'Nhập mã giảm giá',
    apply: 'Áp dụng',
    remove: 'Xóa',
    couponApplied: 'Đã áp dụng: {code} - {description}',
    productValue: 'Tổng giá trị sản phẩm',
    shippingCost: 'Phí giao hàng',
    free: 'Miễn phí',
    discount: 'Giảm giá ({code})',
    total: 'Thành tiền',
    orderPlaced: 'Đặt hàng',
  },

  profile: {
    title: 'Hồ sơ của tôi',
    tabs: {
      account: 'Thông tin tài khoản',
      orders: 'Lịch sử đơn hàng',
      vouchers: 'Ví voucher',
      addresses: 'Sổ địa chỉ',
      reviews: 'Đánh giá & phản hồi',
      notifications: 'Thông báo',
    },
    account: {
      title: 'Thông tin tài khoản',
      loginInfo: 'Thông tin đăng nhập',
      labels: {
        name: 'Họ và tên',
        phone: 'Số điện thoại',
        gender: 'Giới tính',
        dob: 'Ngày sinh',
        height: 'Chiều cao',
        weight: 'Cân nặng',
        email: 'Email',
        password: 'Mật khẩu',
      },
      update: 'CẬP NHẬT',
      password: {
        old: 'Mật khẩu cũ',
        new: 'Mật khẩu mới',
        confirm: 'Nhập lại mật khẩu',
        update: 'CẬP NHẬT MẬT KHẨU',
      },
      edit: {
        title: 'Chỉnh sửa thông tin tài khoản',
        dob: {
          day: 'Ngày',
          month: 'Tháng',
          year: 'Năm',
        },
        gender: {
          male: 'Nam',
          female: 'Nữ',
          other: 'Không tiết lộ',
        },
      },
    },
    orders: {
      title: 'Lịch sử đơn hàng',
      orderId: 'Mã đơn',
      date: 'Ngày',
      total: 'Tổng cộng',
      viewDetails: 'Xem chi tiết',
      reorder: 'Mua lại',
      track: 'Theo dõi đơn',
      review: 'Đánh giá',
      writeReview: 'Viết đánh giá',
      filter: {
        all: 'Tất cả',
        pending: 'Chờ xác nhận',
        shipping: 'Đang giao',
        delivered: 'Đã giao',
        cancelled: 'Đã hủy',
      },
    },
    vouchers: {
      title: 'Ví voucher của tôi',
      empty: {
        title: 'Ví voucher trống',
        description: 'Săn ngay những mã giảm giá hấp dẫn để mua sắm tiết kiệm hơn tại Coolmate.',
        action: 'Săn Voucher',
      },
      remaining: (count: number) => `Còn ${count}`,
      expiry: 'HSD',
      condition: 'Điều kiện',
    },
    addresses: {
      title: 'Địa chỉ của tôi',
      addNew: 'THÊM ĐỊA CHỈ MỚI',
      subTitle: 'Sổ địa chỉ',
      empty: {
        title: 'Sổ địa chỉ trống',
        description: 'Bạn chưa có địa chỉ nào được lưu. Thêm địa chỉ để quá trình đặt hàng nhanh chóng hơn.',
        action: '+ Thêm địa chỉ mới',
      },
      default: 'Mặc định',
      add: {
        title: 'Thêm địa chỉ mới',
        edit: 'Chỉnh sửa địa chỉ',
      },
    },
    reviews: {
      title: 'Đánh giá & Phản hồi',
      pending: 'Chờ đánh giá',
      completed: 'Đã đánh giá',
      pendingTitle: 'Sản phẩm chờ đánh giá',
      completedTitle: 'Đánh giá của bạn',
      order: 'Đơn hàng',
      reply: {
        badge: 'Phản hồi từ shop',
      },
    },
    logout: 'Đăng xuất',
    logoutSuccess: 'Đăng xuất thành công',
  },

  orderTracking: {
    title: 'Theo dõi đơn hàng',
    hero: {
      kicker: 'Theo dõi đơn hàng',
      title: 'Kiểm tra trạng thái giao hàng của bạn',
      subtitle: 'Nhập mã đơn và số điện thoại để cập nhật lộ trình.',
    },
    form: {
      orderId: 'Mã đơn hàng',
      orderIdPlaceholder: 'VD: CM20260301',
      phone: 'Số điện thoại',
      phonePlaceholder: 'VD: 0382253049',
      search: 'Tra cứu đơn hàng',
      searching: 'Đang tra cứu...',
    },
    result: {
      customer: 'Khách hàng',
      eta: 'Dự kiến giao',
      delivered: 'Đã giao',
      trackingNumber: 'Mã vận đơn',
    },
    steps: {
      received: 'Tiếp nhận',
      preparing: 'Đang chuẩn bị hàng',
      shipping: 'Đang giao',
      delivered: 'Giao thành công',
      shippingDesc: 'Đang vận chuyển tới bưu cục đích',
    },
    notFound: {
      title: 'Không tìm thấy đơn hàng',
      desc: 'Kiểm tra lại mã đơn hàng và số điện thoại bạn đã nhập.',
    },
    found: 'Đã tìm thấy đơn hàng',
  },

  returns: {
    title: 'Đổi/Trả hàng',
    hero: {
      kicker: 'Đổi/Trả hàng',
      title: 'Tạo yêu cầu đổi/trả nhanh chóng',
      subtitle: 'Chọn sản phẩm, lý do và đính kèm hình ảnh nếu cần.',
    },
    product: {
      title: 'Sản phẩm trong đơn',
    },
    info: {
      title: 'Thông tin đổi/trả',
      reason: 'Lý do',
      reasons: {
        size: 'Không vừa size',
        defect: 'Lỗi sản phẩm',
        change: 'Hàng giả',
        other: 'Khác',
      },
      description: 'Mô tả chi tiết',
      descriptionPlaceholder: 'Mô tả tình trạng sản phẩm, mong muốn đổi size/màu...',
      image: 'Ảnh minh họa (tùy chọn)',
      upload: {
        title: 'Kéo thả hoặc chọn ảnh',
        hint: 'Hỗ trợ JPG, PNG. Tối đa 3 ảnh',
        button: 'Chọn file',
      },
    },
    resolution: {
      title: 'Hình thức xử lý',
      changeSize: 'Đổi size/màu',
      changeSizeDesc: 'Giữ nguyên sản phẩm, hỗ trợ đổi size/màu nếu còn hàng.',
      refund: 'Trả hàng hoàn tiền',
      refundDesc: 'Hoàn tiền về phương thức thanh toán ban đầu.',
    },
    summary: {
      selectedItems: 'Sản phẩm đã chọn',
      reason: 'Lý do',
      submit: 'Gửi yêu cầu hoàn đơn',
      submitting: 'Đang gửi yêu cầu...',
      submitted: 'Yêu cầu đã gửi thành công — chúng tôi sẽ liên hệ để hướng dẫn quy trình hoàn hàng.',
    },
    validation: {
      selectOne: 'Chọn ít nhất một sản phẩm để đổi/trả',
    },
    submitted: 'Yêu cầu đã gửi thành công (mock)',
  },

  home: {
    mensFashion: 'THỜI TRANG NAM NỔI BẬT',
    womensFashion: 'THỜI TRANG NỮ THỊNH HÀNH',
    loading: 'Đang tải sản phẩm...',
  },

  productDetail: {
    sizeHelp: {
      text: 'Phân vân size? Xem bảng size hoặc nhờ CSKH tư vấn.',
      sizeGuide: 'Bảng size',
      consult: 'Nhờ tư vấn',
    },
    related: 'Sản Phẩm Bạn Có Thể Thích',
  },

  account: {
    orders: {
      title: 'Đơn hàng của tôi',
      subtitle: 'Xem lịch sử đặt hàng và theo dõi trạng thái.',
      orderId: 'Mã đơn',
      orderDate: 'Ngày đặt',
      total: 'Tổng tiền',
      items: 'sản phẩm',
      viewDetails: 'Xem chi tiết',
      noOrders: 'Chưa có đơn hàng nào.',
    },
  },

  search: {
    dropdown: {
      placeholder: 'Tìm kiếm sản phẩm...',
      recentSearches: 'Tìm kiếm gần đây',
      popularKeywords: 'Từ khóa phổ biến',
      clearAll: 'Xóa tất cả',
      viewAll: 'Xem tất cả kết quả',
      viewAllFor: (count: number) => `Xem tất cả ${count} kết quả`,
      noResults: 'Không có kết quả',
      resultsFor: (query: string) => `kết quả cho "${query}"`,
      clearHistory: 'Xóa lịch sử',
    },
    page: {
      title: 'Kết quả tìm kiếm',
      resultsFor: (query: string) => `Kết quả cho: "${query}"`,
      productCount: (count: number) => `${count} sản phẩm`,
      filterBy: 'Lọc theo',
      noQuery: 'Tìm kiếm sản phẩm',
    },
    empty: {
      title: 'Không tìm thấy kết quả',
      subtitle: (query: string) => `Không có sản phẩm nào phù hợp với "${query}"`,
      suggestions: 'Thử tìm với các từ khóa phổ biến:',
      popularKeywords: ['Áo Polo', 'Quần Jeans', 'Áo Thun', 'Hoodie', 'Quần Short'],
      browseCategories: 'hoặc duyệt danh mục sản phẩm',
      browseProducts: 'Duyệt sản phẩm',
    },
    suggestions: {
      title: 'Có thể bạn muốn tìm',
    },
  },

  filter: {
    title: 'Bộ lọc',
    clearAll: 'Xóa tất cả',
    activeFilters: 'Đang lọc:',
    noFilters: 'Tất cả sản phẩm',
    price: {
      label: 'Khoảng giá',
      under200k: 'Dưới 200K',
      from200kto500k: '200K - 500K',
      over500k: 'Trên 500K',
    },
    size: {
      label: 'Kích cỡ',
    },
    color: {
      label: 'Màu sắc',
    },
    sort: {
      label: 'Sắp xếp theo',
      newest: 'Mới nhất',
      bestseller: 'Bán chạy nhất',
      priceAsc: 'Giá: Thấp đến cao',
      priceDesc: 'Giá: Cao đến thấp',
      discount: 'Giảm giá nhiều nhất',
    },
    results: (count: number) => `${count} sản phẩm`,
  },

  productListing: {
    title: 'Tất Cả Sản Phẩm',
    showing: 'Hiển thị',
    of: 'của',
    products: 'sản phẩm',
    noProducts: 'Không tìm thấy sản phẩm nào',
    prevPage: 'Trang trước',
    nextPage: 'Trang sau',
  },
};

export type ClientText = typeof CLIENT_TEXT;
